export const ACCOUNT_START = 'ACCOUNT_START'
export const ACCOUNT_FAIL = 'ACCOUNT_FAIL'
export const AUTHENTICATED_USER = 'AUTHENTICATED_USER'


// =======> USER <=======
export const USER_ACCOUNT_GET_SUCCESS = 'USER_ACCOUNT_GET_SUCCESS'
export const USER_ACCOUNT_UPDATE_SUCCESS = 'USER_ACCOUNT_UPDATE_SUCCESS'
export const USER_ACCOUNT_DELETE_SUCCESS = 'USER_ACCOUNT_DELETE_SUCCESS'

// =======> SUPPLIER <=======
export const SUPPLIER_ACCOUNT_GET_SUCCESS = 'SUPPLIER_ACCOUNT_GET_SUCCESS'
export const SUPPLIER_ACCOUNT_UPDATE_SUCCESS = 'SUPPLIER_ACCOUNT_UPDATE_SUCCESS'
export const SUPPLIER_ACCOUNT_DELETE_SUCCESS = 'SUPPLIER_ACCOUNT_DELETE_SUCCESS'





