export const ORDER_HISTORY = 'ORDER_HISTORY'
export const VIEW_ORDER_HISTORY = 'VIEW_ORDER_HISTORY'
export const VIEW_COMPLETED_ORDER_HISTORY = 'VIEW_COMPLETED_ORDER_HISTORY'
export const ORDER_HISTORY_FAIL = 'VIEW_COMPLETED_ORDER_HISTORY'
